### PR TITLE
try default mul_fxn

### PR DESCRIPTION
**Pull request by tthsqe12**
I suspect the _fmpz_mod_mul2 is at fault.

### CODE REVIEW

**Comment by isuruf** [comment]
Looks like that worked on MSVC

**Comment by tthsqe12** [comment]
everything is fine with the default multiplier.

**Comment by tthsqe12** [comment]
I am going to add test code for the new asm macro. So compiler=cl means msvc?

**Comment by isuruf** [comment]
> So compiler=cl means msvc?

Yes

**Comment by tthsqe12** [comment]
@isuruf is the test folder (the one named "test" and has all the asm macro test code) tested in your appveyor?

**Comment by tthsqe12** [comment]
Well, we have our answer. MSVC is miscompiling the add_ssssaaaaaaaa. Turns out it is not even using the macro and using the fallback, where there seems to be a bug.

**Comment by tthsqe12** [comment]
@isuruf Do you know what recent changes in mingw have broken it for appveyor?
https://ci.appveyor.com/project/tthsqe12/flint2/builds/25284304/job/evetacxh42s6dcag

**Comment by isuruf** [comment]
They released gcc 9.1.0 without Ada support. Can you try changing mingw-w64-i686-toolchain in appveyor.yml to mingw-w64-i686-gcc?

**Comment by tthsqe12** [comment]
still no luck
https://ci.appveyor.com/project/tthsqe12/flint2/builds/25300169/job/cyq5o864ptsofcin

**Comment by isuruf** [comment]
Removing the toolchain package works. It's already installed in appveyor

**Pull request closed without merging**
